"""
Constants for the NHL Scraper.
"""

# Game types
GAME_TYPES = {
    "preseason": 1,
    "regular": 2,
    "playoff": 3,
}

# PBP default columns
PBP_DEFAULT_COLUMNS = [
    "eventId",
    "timeInPeriod",
    "timeRemaining",
    "situationCode",
    "homeTeamDefendingSide",
    "typeCode",
    "typeDescKey",
    "sortOrder",
    "periodDescriptor.number",
    "periodDescriptor.periodType",
    "periodDescriptor.maxRegulationPeriods",
    "details.eventOwnerTeamId",
    "details.losingPlayerId",
    "details.winningPlayerId",
    "details.xCoord",
    "details.yCoord",
    "details.zoneCode",
    "details.hittingPlayerId",
    "details.hitteePlayerId",
    "details.blockingPlayerId",
    "details.shootingPlayerId",
    "details.reason",
    "details.shotType",
    "details.goalieInNetId",
    "details.awaySOG",
    "details.homeSOG",
    "details.playerId",
    "details.typeCode",
    "details.descKey",
    "details.duration",
    "details.committedByPlayerId",
    "details.drawnByPlayerId",
    "pptReplayUrl",
    "details.scoringPlayerId",
    "details.scoringPlayerTotal",
    "details.assist1PlayerId",
    "details.assist1PlayerTotal",
    "details.assist2PlayerId",
    "details.assist2PlayerTotal",
    "details.awayScore",
    "details.homeScore",
    "details.highlightClipSharingUrl",
    "details.highlightClipSharingUrlFr",
    "details.highlightClip",
    "details.highlightClipFr",
    "details.discreteClip",
    "details.discreteClipFr",
    "details.secondaryReason",
    "details.servedByPlayerId",
]

# PBP df columns rename dict
PBP_DF_RENAME = {
    "typeDescKey": "event",
    "periodDescriptor.number": "periodNumber",
    "periodDescriptor.periodType": "periodType",
    "details.eventOwnerTeamId": "teamId",
    "details.xCoord": "xCoord",
    "details.yCoord": "yCoord",
    "details.zoneCode": "zoneCode",
    "details.reason": "reason",
    "details.shotType": "shotType",
    "details.goalieInNetId": "goalieInNetId",
    "details.awaySOG": "awaySOG",
    "details.homeSOG": "homeSOG",
    "details.typeCode": "typeCode",
    "details.descKey": "descKey",
    "details.duration": "duration",
    "details.scoringPlayerTotal": "scoringPlayerTotal",
    "details.assist1PlayerTotal": "assist1PlayerTotal",
    "details.assist2PlayerTotal": "assist2PlayerTotal",
    "details.awayScore": "awayScore",
    "details.homeScore": "homeScore",
    "details.secondaryReason": "secondaryReason",
    "details.servedByPlayerId": "servedByPlayerId",
}
